#!/usr/bin/env php
<?php
/**
 * 初始化
 */
require __DIR__ . '/vendor/autoload.php';

use mon\orm\Db;
use mon\env\Config;
use mon\assets\Util;
use mon\orm\exception\MondbException;

Config::instance()->load(__DIR__ . '/config/config.php');
$config = Config::instance()->get();

try {
    echo 'Setup is starting...' . PHP_EOL;

    Db::setConfig($config['database']);
    Db::startTrans();

    $total = 0;
    // 安装资产表
    $tabname = $config['system']['assets']['name'];
    $tabtotal = $config['system']['assets']['total'];
    $total += Util::installAsstes($tabname, $tabtotal);
    // 安装日志表
    $tabname = $config['system']['log']['name'];
    $tabtotal = $config['system']['log']['total'];
    $total += Util::installLog($tabname, $tabtotal);

    Db::commit();
    echo 'Total number of tables created: ' . $total . PHP_EOL;
    echo 'installation complete, success!' . PHP_EOL;
    exit();
} catch (MondbException $e) {
    Db::rollback();
    echo 'MondbException: ' . PHP_EOL;
    echo 'File: ' . $e->getFile() . PHP_EOL;
    echo 'Line: ' . $e->getLine() . PHP_EOL;
    echo 'Message: ' . $e->getMessage() . PHP_EOL;
    exit();
} catch (Exception $e) {
    Db::rollback();
    echo 'Exception: ' . PHP_EOL;
    echo 'File: ' . $e->getFile() . PHP_EOL;
    echo 'Line: ' . $e->getLine() . PHP_EOL;
    echo 'Message: ' . $e->getMessage() . PHP_EOL;
    exit();
}
